### ISSUE TITLE
Implement `api/tools/quick-exercises` endpoint that takes the data and responds with a AI generated simple response

### ISSUE THREAD

**Issue by Kuroashi1995** [Kuroashi1995/teacher-assistant-server#4]
# Overview
Take the implementation of #3 and create the endpoint with a simple response
## Tasks

- [x] Take the data from the request
- [x] Create either a chat completion or an assistant completion with the provided data
- [x] Implement a response that sends only the message returned from OpenAI

**Comment by Kuroashi1995** [comment]
Functionality tested and completed
